name: DevBuild
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
<<<<<<< HEAD
        os: [ubuntu-latest, windows-latest, macos-latest]

=======
        os: [windows-latest, macos-latest, ubuntu-latest]
        build_type: [RelWithDebInfo, Debug]
        ui: [gui, cli]
        scripting: [lua, noscripts]
        exclude:
          - build_type: Debug
            ui: gui
          - build_type: RelWithDebInfo
            ui: cli
          - build_type: RelWithDebInfo
            scripting: noscripts
>>>>>>> upstream/main
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
<<<<<<< HEAD
    - uses: hendrikmuhs/ccache-action@main
      with:
        key: ${{ matrix.os }}
    - uses: turtlesec-no/get-ninja@main
      if: runner.os == 'Windows'

    - name: ubuntu-latest
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update -y
        sudo apt-get upgrade -y
        sudo apt-get install -y g++ clang libc++-dev libc++abi-dev cmake ninja-build libx11-dev libxcursor-dev libxi-dev libgl1-mesa-dev libfontconfig1-dev unzip
        cd "$GITHUB_WORKSPACE"
        wget https://github.com/aseprite/skia/releases/download/m102-861e4743af/Skia-Linux-Release-x64-libc++.zip
        mkdir $HOME/deps
        mkdir $HOME/deps/skia
        mv Skia-Linux-Release-x64-libc++.zip $HOME/deps/skia/
        cd $HOME/deps/skia
        unzip Skia-Linux-Release-x64-libc++.zip
        rm Skia-Linux-Release-x64-libc++.zip
        cd "$GITHUB_WORKSPACE"
        mkdir build
        cd "$GITHUB_WORKSPACE/build"
        export CC=clang
        export CXX=clang++
        cmake \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DCMAKE_CXX_FLAGS:STRING=-stdlib=libc++ \
          -DCMAKE_EXE_LINKER_FLAGS:STRING=-stdlib=libc++ \
          -DLAF_BACKEND=skia \
          -DSKIA_DIR=$HOME/deps/skia \
          -DSKIA_LIBRARY_DIR=$HOME/deps/skia/out/Release-x64 \
          -DSKIA_LIBRARY=$HOME/deps/skia/out/Release-x64/libskia.a \
          -G Ninja \
          ..
        ninja aseprite

    - name: windows-latest
      if: runner.os == 'Windows'
      run: |
        choco uninstall mingw
        choco upgrade all
        choco install llvm
        Remove-Item -Recurse -Force C:/Strawberry
        Remove-Item -Recurse -Force 'C:/Program Files/OpenSSL'
        Set-Location 'D:/a/aseprite/aseprite'
        curl -LO https://github.com/aseprite/skia/releases/download/m102-861e4743af/Skia-Windows-Release-x64.zip
        New-Item -ItemType Directory -Path 'D:/a/aseprite/deps'
        New-Item -ItemType Directory -Path 'D:/a/aseprite/deps/skia'
        Move-Item 'Skia-Windows-Release-x64.zip' 'D:/a/aseprite/deps/skia/'
        Set-Location 'D:/a/aseprite/deps/skia'
        Expand-Archive 'Skia-Windows-Release-x64.zip' -DestinationPath .
        Remove-Item 'Skia-Windows-Release-x64.zip'
        Set-Location 'D:/a/aseprite/aseprite'
        New-Item -ItemType Directory -Path 'build'

    - name: windows-latest-compile
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        call "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Common7/Tools/VsDevCmd.bat" -arch=x64
        cd D:/a/aseprite/aseprite/build
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAF_BACKEND=skia -DSKIA_DIR=D:/a/aseprite/deps/skia -DSKIA_LIBRARY_DIR=D:/a/aseprite/deps/skia/out/Release-x64 -DSKIA_LIBRARY=D:/a/aseprite/deps/skia/out/Release-x64/skia.lib -G Ninja ..
        ninja aseprite

    - name: macos-latest
      if: runner.os == 'macOS'
      run: |
        brew upgrade
        brew install cmake
        brew install ninja
        cd "$GITHUB_WORKSPACE"
        wget https://github.com/aseprite/skia/releases/download/m102-861e4743af/Skia-macOS-Release-x64.zip
        mkdir $HOME/deps
        mkdir $HOME/deps/skia
        mv Skia-macOS-Release-x64.zip $HOME/deps/skia/
        cd $HOME/deps/skia
        unzip Skia-macOS-Release-x64.zip
        rm Skia-macOS-Release-x64.zip
        cd "$GITHUB_WORKSPACE"
        mkdir build
        cd "$GITHUB_WORKSPACE/build"
        cmake \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        -DCMAKE_OSX_ARCHITECTURES=x86_64 \
        -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 \
        -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk \
        -DLAF_BACKEND=skia \
        -DSKIA_DIR=$HOME/deps/skia \
        -DSKIA_LIBRARY_DIR=$HOME/deps/skia/out/Release-x64 \
        -DSKIA_LIBRARY=$HOME/deps/skia/out/Release-x64/libskia.a \
        -G Ninja \
        ..
        ninja aseprite

    - uses: actions/upload-artifact@v4
      with:
        name: devbuild-${{ matrix.os }}
        path: build/bin/*
        retention-days: 30
=======
    - name: Install Dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y \
          libpixman-1-dev libfreetype6-dev libharfbuzz-dev zlib1g-dev \
          libx11-dev libxcursor-dev libxi-dev libgl1-mesa-dev
    - name: Install Skia
      if: ${{ matrix.ui == 'gui' }}
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Windows" ]] ; then
          choco install wget -y --no-progress
          wget https://github.com/aseprite/skia/releases/download/m102-861e4743af/Skia-Windows-Release-x64.zip
          unzip Skia-Windows-Release-x64.zip -d skia
        elif [[ "${{ runner.os }}" == "macOS" ]] ; then
          wget https://github.com/aseprite/skia/releases/download/m102-861e4743af/Skia-macOS-Release-arm64.zip
          unzip Skia-macOS-Release-arm64.zip -d skia
        else
          wget https://github.com/aseprite/skia/releases/download/m102-861e4743af/Skia-Linux-Release-x64-libstdc++.zip
          unzip Skia-Linux-Release-x64-libstdc++.zip -d skia
        fi
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1
      if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
      with:
        key: ${{ matrix.os }}-${{ matrix.ui }}-${{ matrix.scripting }}-${{ matrix.build_type }}
    - uses: aseprite/get-ninja@main
    - uses: ilammy/msvc-dev-cmd@v1
      if: runner.os == 'Windows'
    - name: Generating Makefiles
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Windows" ]] ; then
          export enable_ccache=off
        else
          export enable_ccache=on
        fi

        if [[ "${{ matrix.ui }}" == "gui" ]] ; then
          export laf_backend=skia
        else
          export laf_backend=none
        fi

        if [[ "${{ matrix.scripting }}" == "lua" ]] ; then
          export enable_scripting=on
        else
          export enable_scripting=off
        fi

        if [[ "${{ runner.os }}" == "macOS" ]] ; then
          export skia_arch=arm64
        else
          export skia_arch=x64
        fi

        cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 \
          -DENABLE_TESTS=ON \
          -DENABLE_SCRIPTING=$enable_scripting \
          -DENABLE_CCACHE=$enable_ccache \
          -DLAF_BACKEND=$laf_backend \
          -DSKIA_DIR=skia \
          -DSKIA_LIBRARY_DIR=skia/out/Release-$skia_arch
    - name: Compiling
      shell: bash
      run: |
        cd build && ninja
    - name: Running C++ Tests
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Linux" ]] ; then
          export XVFB=xvfb-run
        fi
        cd build && $XVFB ctest --output-on-failure
    - name: Running CLI Tests
      if: ${{ matrix.scripting == 'lua' }}
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Linux" ]] ; then
          export XVFB=xvfb-run
        fi
        export ASEPRITE=$PWD/build/bin/aseprite
        cd tests
        $XVFB bash run-tests.sh
>>>>>>> upstream/main
